"""Add-Unique-index

Revision ID: 3edd66ab9dfe
Revises: c2b3de753a44
Create Date: 2025-07-27 17:41:21.311083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edd66ab9dfe'
down_revision: Union[str, None] = 'c2b3de753a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_diary_meta_user_id_date', 'diary_meta', ['user_id', 'date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diary_meta_user_id_date', table_name='diary_meta')
    # ### end Alembic commands ###
