"""create-tag-table

Revision ID: 97a63821c920
Revises: 75b6168e2899
Create Date: 2025-08-18 22:52:54.882952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97a63821c920'
down_revision: Union[str, None] = '75b6168e2899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('diary_meta_id', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('diary_meta_id', 'label', name='uq_diary_meta_label')
    )
    op.create_index('ix_tags_diary_meta_id', 'tags', ['diary_meta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_diary_meta_id', table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
